version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: antongrenkov/taski_backend:latest
    # platform: linux/amd64
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    image: antongrenkov/taski_frontend:latest
    # platform: linux/amd64
    env_file: .env
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: antongrenkov/taski_gateway:latest
    # platform: linux/amd64
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80